### ISSUE TITLE
LDAP users continue to work after LDAP integration is disabled

### ISSUE THREAD

**Issue by tfarmer00** [alexpozzi/pimcore-ldap-bundle#6]
When disabling the plugin, LDAP created users continue to work. When LDAP is no longer working, those users should not be able to authenticate.

**Comment by alexpozzi** [comment]
This is a wanted behavior, the [default data mapper](https://github.com/alexpozzi/pimcore-ldap-bundle#custom-data-mapper) sync the user password as well in order to be able not to loose imported LDAP users in case, in the future, you'll want to disable this functionality.

BTW, as there isn't in Pimcore a standard way to define that a user is coming from LDAP (or at least at the time this bundle was written), it's gonna be hard to implement a feature like the one you are asking for in a standard way.

I suggest you to fork the project and implement your own logic for that.
